Refactor/update dependencies
atls/grpc pull request #9
Opened 2024-10-21 12:43 UTC by OsirisAnubiz

2024-10-21 14:56 UTC, OsirisAnubiz commented
@Nelfimov готово. Единственное что не работает `yarn proto:generate` и `yarn proto:lint`. Не знаю должно ли так быть. `build` и `prepack` работает

2024-10-22 06:24 UTC, Nelfimov requested changes
1. перевести на есм
2. бампнуть вручную на мажорную версию

2024-10-23 09:40 UTC, OsirisAnubiz commented
@Nelfimov библиотека `google-protobuf` не поддерживает esm. На их [github репозитории](https://github.com/protocolbuffers/protobuf-javascript) написанно следующее:
```
The library is currently compatible with:
1. CommonJS-style imports (eg. var protos = require('my-protos');)
2. Closure-style imports (eg. goog.require('my.package.MyProto');)
Support for ES6-style imports is not implemented yet. Browsers can be supported by using Browserify, webpack, Closure Compiler, etc. to resolve imports at compile time
```

Мне использовать `createRequire` или какой-то из предложенных ими вариантов?

2024-10-23 10:03 UTC, OsirisAnubiz commented
сделал через `"moduleResolution": "Node"

2024-10-23 11:46 UTC, Nelfimov commented
`createRequire` и `NodeNext`

2024-10-24 05:34 UTC, Nelfimov requested changes

2024-10-24 05:34 UTC, Nelfimov commented on .yarnrc.yml
> +      long: '*'
нужно ли нам это после бампа версий?

2024-10-24 05:34 UTC, Nelfimov commented on packages/grpc-error-status/package.json
> +    "proto:generate": "PATH=$PATH:$(yarn bin protoc-gen-ts) buf generate",
скрипты работают? Помню у них cli менялось

2024-10-24 08:38 UTC, OsirisAnubiz commented on .yarnrc.yml
> +      long: '*'
Нет, удалил

2024-10-24 10:14 UTC, merged